/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      description: string
      subject_type: string
      subject_id: number
      causer: string
      properties: string
      ip_address: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      subjectType: string
      subjectId: number
      ipAddress: string
      userId: number
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      bio: string
      avatar: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      userId: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      position: number
      card_limit: number
      color: string
      createdAt: string
      updatedAt: string | null
      boardId: number
      cardLimit: number
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      icon: string
      color: string
      position: number
      archived: boolean
      createdAt: string
      updatedAt: string | null
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: "queued" | "sent" | "failed" | "bounced" | "complained"
      provider_message_id: string
      error: string
      sent_at: string
      opened_at: string
      clicked_at: string
      createdAt: string
      updatedAt: string | null
      campaignId: number
      subscriberId: number
      emailListId: number
      providerMessageId: string
      sentAt: string
      openedAt: string
      clickedAt: string
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      type: "email" | "sms" | "push" | "social" | "multi-channel"
      status: "draft" | "scheduled" | "sending" | "sent" | "paused" | "cancelled" | "failed" | "active" | "completed" | "archived"
      subject: string
      template: string
      text: string
      from_name: string
      from_address: string
      email_list_id: number
      scheduled_at: string
      sent_at: string
      audience_size: number
      sent_count: number
      open_rate: number
      click_rate: number
      conversion_rate: number
      budget: number
      spent: number
      start_date: string
      end_date: string
      createdAt: string
      updatedAt: string | null
      fromName: string
      fromAddress: string
      emailListId: number
      scheduledAt: string
      sentAt: string
      audienceSize: number
      sentCount: number
      openRate: number
      clickRate: number
      conversionRate: number
      startDate: string
      endDate: string
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: string
      createdAt: string
      updatedAt: string | null
      cardId: number
      userId: number
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: number
      board_id: number
      title: string
      description: string
      position: number
      created_by_user_id: number
      due_date: string
      archived: boolean
      board_column_id: number
      user_id: number
      createdAt: string
      updatedAt: string | null
      columnId: number
      boardId: number
      createdByUserId: number
      dueDate: string
      boardColumnId: number
      userId: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: number
      unit_price: number
      total_price: number
      tax_rate: number
      tax_amount: number
      discount_percentage: number
      discount_amount: number
      product_name: string
      product_sku: string
      product_image: string
      notes: string
      cart_id: number
      createdAt: string
      updatedAt: string | null
      unitPrice: number
      totalPrice: number
      taxRate: number
      taxAmount: number
      discountPercentage: number
      discountAmount: number
      productName: string
      productSku: string
      productImage: string
      cartId: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "active" | "abandoned" | "converted" | "expired"
      total_items: number
      subtotal: number
      tax_amount: number
      discount_amount: number
      total: number
      expires_at: string
      currency: string
      notes: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
      createdAt: string
      updatedAt: string | null
      totalItems: number
      taxAmount: number
      discountAmount: number
      expiresAt: string
      appliedCouponId: string
      customerId: number
      couponId: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      slug: string
      image_url: string
      is_active: boolean
      parent_category_id: string
      display_order: number
      createdAt: string
      updatedAt: string | null
      imageUrl: string
      isActive: boolean
      parentCategoryId: string
      displayOrder: number
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: string
      author_email: string
      content: string
      body: string
      post_title: string
      status: "pending" | "approved" | "spam" | "trash"
      ip_address: string
      user_agent: string
      is_approved: number
      post_id: number
      user_id: number
      createdAt: string
      updatedAt: string | null
      authorName: string
      authorEmail: string
      postTitle: string
      ipAddress: string
      userAgent: string
      isApproved: number
      postId: number
      userId: number
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      description: string
      status: "Active" | "Scheduled" | "Expired"
      is_active: boolean
      discount_type: "fixed_amount" | "percentage"
      discount_value: number
      min_order_amount: number
      max_discount_amount: number
      free_product_id: string
      usage_limit: number
      usage_count: number
      start_date: string
      end_date: string
      product_id: number
      createdAt: string
      updatedAt: string | null
      isActive: boolean
      discountType: "fixed_amount" | "percentage"
      discountValue: number
      minOrderAmount: number
      maxDiscountAmount: number
      freeProductId: string
      usageLimit: number
      usageCount: number
      startDate: string
      endDate: string
      productId: number
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      total_spent: number
      last_order: string
      status: "Active" | "Inactive"
      avatar: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      totalSpent: number
      lastOrder: string
      userId: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      driver: string
      vehicle: string
      stops: number
      delivery_time: number
      total_distance: number
      last_active: string
      createdAt: string
      updatedAt: string | null
      deliveryTime: number
      totalDistance: number
      lastActive: string
    }
    demo_requests: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      farm_name: string
      segment: string
      hectares: number
      message: string
      status: "new" | "contacted" | "scheduled" | "closed"
      source: string
      createdAt: string
      updatedAt: string | null
      farmName: string
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commit_hash: string
      commit_message: string
      branch: string
      status: string
      environment: string
      duration: number
      author: string
      url: string
      error_log: string
      createdAt: string
      updatedAt: string | null
      commitHash: string
      commitMessage: string
      errorLog: string
    }
    detections: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      mission_id: number
      field_id: number
      kind: "weed" | "disease" | "pest" | "nutrient" | "moisture" | "compaction" | "wildlife" | "gap" | "livestock"
      label: string
      confidence: number
      severity: "low" | "medium" | "high"
      area_m2: number
      x: number
      y: number
      latitude: number
      longitude: number
      status: "open" | "review" | "confirmed" | "treated" | "dismissed"
      createdAt: string
      updatedAt: string | null
      missionId: number
      fieldId: number
      areaM2: number
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      download_limit: number
      expiry_days: number
      requires_login: boolean
      automatic_delivery: boolean
      status: "active" | "inactive"
      createdAt: string
      updatedAt: string | null
      downloadLimit: number
      expiryDays: number
      requiresLogin: boolean
      automaticDelivery: boolean
    }
    drivers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      phone: string
      vehicle_number: string
      license: string
      status: "active" | "on_delivery" | "on_break"
      user_id: number
      createdAt: string
      updatedAt: string | null
      vehicleNumber: string
      userId: number
    }
    drones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      farm_id: number
      callsign: string
      model: string
      payload: "rgb" | "multispectral" | "thermal" | "lidar" | "hopper"
      status: "docked" | "in_flight" | "charging" | "maintenance" | "offline"
      station: string
      battery_percent: number
      flight_hours: number
      createdAt: string
      updatedAt: string | null
      farmId: number
      batteryPercent: number
      flightHours: number
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      subscribed_at: string
      unsubscribed_at: string
      createdAt: string
      updatedAt: string | null
      emailListId: number
      subscriberId: number
      subscribedAt: string
      unsubscribedAt: string
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      subscriber_count: number
      active_count: number
      unsubscribed_count: number
      bounced_count: number
      status: "active" | "inactive" | "archived"
      is_public: number
      double_opt_in: number
      createdAt: string
      updatedAt: string | null
      subscriberCount: number
      activeCount: number
      unsubscribedCount: number
      bouncedCount: number
      isPublic: number
      doubleOptIn: number
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: string
      message: string
      stack: string
      status: number
      additional_info: string
      createdAt: string
      updatedAt: string | null
      additionalInfo: string
    }
    failed_jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      connection: string
      queue: string
      payload: string
      exception: string
      failed_at: string
      createdAt: string
      updatedAt: string | null
      failedAt: string
    }
    farm_capabilities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      farm_id: number
      field_id: number
      feature_slug: string
      status: "active" | "paused" | "requested"
      cadence_days: number
      notes: string
      last_scheduled_at: string
      createdAt: string
      updatedAt: string | null
      farmId: number
      fieldId: number
      featureSlug: string
      cadenceDays: number
      lastScheduledAt: string
    }
    farms: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      name: string
      slug: string
      region: string
      segment: string
      hectares: number
      user_id: number
      createdAt: string
      updatedAt: string | null
      deletedAt: string | null
      userId: number
    }
    features: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      slug: string
      name: string
      category: "detect" | "act" | "operate"
      tagline: string
      summary: string
      problem: string
      steps: string
      sensors: string
      outputs: string
      readings: string
      cadence: string
      use_case_slugs: string
      sort_order: number
      createdAt: string
      updatedAt: string | null
      useCaseSlugs: string
      sortOrder: number
    }
    fields: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      farm_id: number
      name: string
      slug: string
      crop: string
      hectares: number
      status: "active" | "fallow" | "archived"
      latitude: number
      longitude: number
      boundary: string
      createdAt: string
      updatedAt: string | null
      deletedAt: string | null
      farmId: number
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      initial_balance: number
      current_balance: number
      currency: string
      status: string
      purchaser_id: string
      recipient_email: string
      recipient_name: string
      personal_message: string
      is_digital: boolean
      is_reloadable: boolean
      is_active: boolean
      expiry_date: string
      last_used_date: string
      template_id: string
      customer_id: number
      createdAt: string
      updatedAt: string | null
      initialBalance: number
      currentBalance: number
      purchaserId: string
      recipientEmail: string
      recipientName: string
      personalMessage: string
      isDigital: boolean
      isReloadable: boolean
      isActive: boolean
      expiryDate: string
      lastUsedDate: string
      templateId: string
      customerId: number
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: string
      payload: string
      attempts: number
      available_at: number
      reserved_at: string
      createdAt: string
      updatedAt: string | null
      availableAt: number
      reservedAt: string
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      color: string
      createdAt: string
      updatedAt: string | null
      boardId: number
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      template: "Standard License" | "Premium License" | "Enterprise License"
      expiry_date: string
      status: "active" | "inactive" | "unassigned"
      customer_id: number
      product_id: number
      order_id: number
      createdAt: string
      updatedAt: string | null
      expiryDate: string
      customerId: number
      productId: number
      orderId: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: number
      type: "warning" | "error" | "info" | "success"
      source: "file" | "cli" | "system"
      message: string
      project: string
      stacktrace: string
      file: string
      createdAt: string
      updatedAt: string | null
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: string
      points: number
      source: string
      source_reference_id: string
      description: string
      expiry_date: string
      is_used: boolean
      createdAt: string
      updatedAt: string | null
      walletId: string
      sourceReferenceId: string
      expiryDate: string
      isUsed: boolean
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      points_required: number
      reward_type: string
      discount_percentage: number
      free_product_id: string
      is_active: boolean
      expiry_days: number
      image_url: string
      product_id: number
      createdAt: string
      updatedAt: string | null
      pointsRequired: number
      rewardType: string
      discountPercentage: number
      freeProductId: string
      isActive: boolean
      expiryDays: number
      imageUrl: string
      productId: number
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: string
      description: string
      country: string
      featured: boolean
      createdAt: string
      updatedAt: string | null
    }
    missions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      farm_id: number
      field_id: number
      drone_id: number
      purpose: string
      status: "scheduled" | "flying" | "processing" | "complete" | "weather_cancelled" | "failed"
      flown_at: string
      hectares_covered: number
      duration_minutes: number
      resolution_cm: number
      summary: string
      orthomosaic_url: string
      orthomosaic_bounds: string
      orthomosaic_resolution_cm: number
      cancellation_reason: string
      createdAt: string
      updatedAt: string | null
      farmId: number
      fieldId: number
      droneId: number
      flownAt: string
      hectaresCovered: number
      durationMinutes: number
      resolutionCm: number
      orthomosaicUrl: string
      orthomosaicBounds: string
      orthomosaicResolutionCm: number
      cancellationReason: string
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: "email" | "sms" | "push" | "slack" | "webhook"
      channel: string
      recipient: string
      subject: string
      body: string
      status: "pending" | "sent" | "delivered" | "failed" | "read"
      read_at: string
      sent_at: string
      metadata: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      readAt: string
      sentAt: string
      userId: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: number
      price: number
      special_instructions: string
      order_id: number
      product_id: number
      createdAt: string
      updatedAt: string | null
      specialInstructions: string
      orderId: number
      productId: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: string
      total_amount: number
      tax_amount: number
      discount_amount: number
      delivery_fee: number
      tip_amount: number
      order_type: string
      delivery_address: string
      special_instructions: string
      estimated_delivery_time: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
      createdAt: string
      updatedAt: string | null
      totalAmount: number
      taxAmount: number
      discountAmount: number
      deliveryFee: number
      tipAmount: number
      orderType: string
      deliveryAddress: string
      specialInstructions: string
      estimatedDeliveryTime: string
      appliedCouponId: string
      customerId: number
      couponId: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      template: string
      views: number
      published_at: string
      conversions: number
      author_id: number
      createdAt: string
      updatedAt: string | null
      publishedAt: string
      authorId: number
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      last_four: number
      brand: string
      exp_month: number
      exp_year: number
      is_default: boolean
      provider_id: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      lastFour: number
      expMonth: number
      expYear: number
      isDefault: boolean
      providerId: string
      userId: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      key: string
      unit_price: number
      status: string
      image: string
      provider_id: string
      createdAt: string
      updatedAt: string | null
      unitPrice: number
      providerId: string
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      amount: number
      type: string
      provider_id: string
      user_id: number
      payment_method_id: number
      createdAt: string
      updatedAt: string | null
      providerId: string
      userId: number
      paymentMethodId: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      method: string
      status: string
      currency: string
      reference_number: string
      card_last_four: string
      card_brand: string
      billing_email: string
      transaction_id: string
      payment_provider: string
      refund_amount: number
      notes: string
      order_id: number
      customer_id: number
      createdAt: string
      updatedAt: string | null
      referenceNumber: string
      cardLastFour: string
      cardBrand: string
      billingEmail: string
      transactionId: string
      paymentProvider: string
      refundAmount: number
      orderId: number
      customerId: number
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      poster: string
      content: string
      excerpt: string
      views: number
      published_at: string
      status: "published" | "draft" | "archived"
      is_featured: number
      author_id: number
      createdAt: string
      updatedAt: string | null
      publishedAt: string
      isFeatured: number
      authorId: number
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      mac_address: string
      location: string
      terminal: string
      status: "online" | "offline" | "warning"
      last_ping: number
      print_count: number
      createdAt: string
      updatedAt: string | null
      macAddress: string
      lastPing: number
      printCount: number
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      abbreviation: string
      type: string
      description: string
      is_default: boolean
      product_id: number
      createdAt: string
      updatedAt: string | null
      isDefault: boolean
      productId: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: string
      type: string
      description: string
      options: string
      status: "active" | "inactive" | "draft"
      product_id: number
      createdAt: string
      updatedAt: string | null
      productId: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      price: number
      image_url: string
      is_available: boolean
      inventory_count: number
      preparation_time: number
      allergens: string
      nutritional_info: string
      category_id: number
      manufacturer_id: number
      createdAt: string
      updatedAt: string | null
      imageUrl: string
      isAvailable: boolean
      inventoryCount: number
      preparationTime: number
      nutritionalInfo: string
      categoryId: number
      manufacturerId: number
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: string
      document: string
      timestamp: string
      status: "success" | "failed" | "warning"
      size: number
      pages: number
      duration: number
      metadata: string
      print_device_id: number
      createdAt: string
      updatedAt: string | null
      printDeviceId: number
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: string
      type: string
      status: string
      notes: string
      downloads: number
      author: string
      createdAt: string
      updatedAt: string | null
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD"
      path: string
      status_code: number
      duration_ms: number
      ip_address: string
      memory_usage: number
      user_agent: string
      error_message: string
      createdAt: string
      updatedAt: string | null
      deletedAt: string | null
      statusCode: number
      durationMs: number
      ipAddress: string
      memoryUsage: number
      userAgent: string
      errorMessage: string
    }
    reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rating: number
      title: string
      content: string
      is_verified_purchase: boolean
      is_approved: boolean
      is_featured: boolean
      helpful_votes: number
      unhelpful_votes: number
      purchase_date: string
      images: string
      product_id: number
      customer_id: number
      createdAt: string
      updatedAt: string | null
      isVerifiedPurchase: boolean
      isApproved: boolean
      isFeatured: boolean
      helpfulVotes: number
      unhelpfulVotes: number
      purchaseDate: string
      productId: number
      customerId: number
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      base_rate: number
      free_shipping: number
      status: "active" | "inactive" | "draft"
      createdAt: string
      updatedAt: string | null
      baseRate: number
      freeShipping: number
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: number
      weight_to: number
      rate: number
      shipping_method_id: number
      shipping_zone_id: number
      createdAt: string
      updatedAt: string | null
      weightFrom: number
      weightTo: number
      shippingMethodId: number
      shippingZoneId: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      countries: string
      regions: string
      postal_codes: string
      status: "active" | "inactive" | "draft"
      shipping_method_id: number
      createdAt: string
      updatedAt: string | null
      postalCodes: string
      shippingMethodId: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: string
      platform: "twitter" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube"
      status: "draft" | "scheduled" | "published" | "failed"
      scheduled_at: string
      published_at: string
      likes: number
      shares: number
      comments: number
      reach: number
      image_url: string
      external_id: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      scheduledAt: string
      publishedAt: string
      imageUrl: string
      externalId: string
      userId: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      source: string
      subscriber_id: number
      createdAt: string
      updatedAt: string | null
      subscriberId: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      unsubscribed_at: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      unsubscribedAt: string
      userId: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      plan: string
      provider_id: string
      provider_status: string
      unit_price: number
      provider_type: string
      provider_price_id: string
      quantity: number
      trial_ends_at: string
      ends_at: string
      last_used_at: string
      user_id: number
      createdAt: string
      updatedAt: string | null
      providerId: string
      providerStatus: string
      unitPrice: number
      providerType: string
      providerPriceId: string
      trialEndsAt: string
      endsAt: string
      lastUsedAt: string
      userId: number
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      post_count: number
      color: string
      createdAt: string
      updatedAt: string | null
      postCount: number
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      rate: number
      type: string
      country: string
      region: "North America" | "South America" | "Europe" | "Asia" | "Africa" | "Oceania" | "Antarctica"
      status: "active" | "inactive"
      is_default: boolean
      createdAt: string
      updatedAt: string | null
      isDefault: boolean
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      member_count: number
      status: string
      createdAt: string
      updatedAt: string | null
      memberCount: number
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      status: string
      payment_method: string
      payment_details: string
      transaction_reference: string
      loyalty_points_earned: number
      loyalty_points_redeemed: number
      order_id: number
      createdAt: string
      updatedAt: string | null
      paymentMethod: string
      paymentDetails: string
      transactionReference: string
      loyaltyPointsEarned: number
      loyaltyPointsRedeemed: number
      orderId: number
    }
    treatment_maps: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      mission_id: number
      field_id: number
      product: string
      zones: string
      treated_hectares: number
      field_hectares: number
      rate_per_hectare: number
      format: "isoxml" | "shapefile" | "geojson" | "csv"
      status: "draft" | "ready" | "applied" | "superseded"
      notes: string
      createdAt: string
      updatedAt: string | null
      missionId: number
      fieldId: number
      treatedHectares: number
      fieldHectares: number
      ratePerHectare: number
    }
    use_cases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      slug: string
      name: string
      segment: "arable" | "permanent" | "protected" | "livestock" | "operator"
      tagline: string
      summary: string
      challenge: string
      approach: string
      season: string
      feature_slugs: string
      outcomes: string
      scale: string
      sort_order: number
      createdAt: string
      updatedAt: string | null
      featureSlugs: string
      sortOrder: number
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_verified_at: string | null
      password_changed_at: string | null
      two_factor_secret: string | null
      two_factor_enabled: boolean | null
      two_factor_last_used_step: number | null
      stripe_id: string | null
      name: string
      email: string
      password: string
      avatar: string
      createdAt: string
      updatedAt: string | null
      emailVerifiedAt: string | null
      passwordChangedAt: string | null
      twoFactorSecret: string | null
      twoFactorEnabled: boolean | null
      twoFactorLastUsedStep: number | null
      stripeId: string | null
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      quantity: number
      notification_preference: "sms" | "email" | "both"
      source: string
      notes: string
      status: "waiting" | "purchased" | "notified" | "cancelled"
      notified_at: string
      purchased_at: string
      cancelled_at: string
      product_id: number
      customer_id: number
      createdAt: string
      updatedAt: string | null
      notificationPreference: "sms" | "email" | "both"
      notifiedAt: string
      purchasedAt: string
      cancelledAt: string
      productId: number
      customerId: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      party_size: number
      check_in_time: string
      table_preference: "indoor" | "bar" | "booth" | "no_preference"
      status: "waiting" | "seated" | "cancelled" | "no_show"
      quoted_wait_time: number
      actual_wait_time: number
      queue_position: number
      seated_at: string
      no_show_at: string
      cancelled_at: string
      customer_id: number
      createdAt: string
      updatedAt: string | null
      partySize: number
      checkInTime: string
      tablePreference: "indoor" | "bar" | "booth" | "no_preference"
      quotedWaitTime: number
      actualWaitTime: number
      queuePosition: number
      seatedAt: string
      noShowAt: string
      cancelledAt: string
      customerId: number
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: "disconnection" | "error" | "success"
      socket: string
      details: string
      time: number
      createdAt: string
      updatedAt: string | null
    }
  }
}

export {}
