-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "herds" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "farm_id" INTEGER not null REFERENCES "farms"("id"),
  "field_id" INTEGER REFERENCES "fields"("id"),
  "name" TEXT not null,
  "slug" TEXT not null,
  "species" TEXT CHECK ("species" IN ('cattle', 'sheep', 'goats', 'horses')) not null default 'cattle',
  "mob_class" TEXT,
  "head_count" INTEGER default 0,
  "expected_head" INTEGER default 0,
  "pressure_profile" TEXT CHECK ("pressure_profile" IN ('calm', 'standard', 'shy')) default 'standard',
  "status" TEXT CHECK ("status" IN ('grazing', 'moving', 'housed', 'archived')) default 'grazing',
  "notes" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "deleted_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "herds_slug_unique" ON "herds" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "herds_uuid_unique" ON "herds" ("uuid");
