-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "features_slug_unique" ON "features" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "features_uuid_unique" ON "features" ("uuid");
