-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "use_cases_slug_unique" ON "use_cases" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "use_cases_uuid_unique" ON "use_cases" ("uuid");
