-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_detections" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "mission_id" INTEGER not null REFERENCES "missions"("id"),
  "field_id" INTEGER REFERENCES "fields"("id"),
  "kind" TEXT CHECK ("kind" IN ('weed', 'disease', 'pest', 'nutrient', 'moisture', 'compaction', 'wildlife', 'gap', 'livestock', 'fence')) not null,
  "label" TEXT not null,
  "confidence" INTEGER default 0,
  "severity" TEXT CHECK ("severity" IN ('low', 'medium', 'high')) default 'low',
  "area_m2" INTEGER default 0,
  "x" INTEGER,
  "y" INTEGER,
  "latitude" INTEGER,
  "longitude" INTEGER,
  "status" TEXT CHECK ("status" IN ('open', 'review', 'confirmed', 'treated', 'dismissed')) default 'open',
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_detections" ("id", "mission_id", "field_id", "kind", "label", "confidence", "severity", "area_m2", "x", "y", "latitude", "longitude", "status", "created_at", "updated_at", "uuid") SELECT "id", "mission_id", "field_id", "kind", "label", "confidence", "severity", "area_m2", "x", "y", "latitude", "longitude", "status", "created_at", "updated_at", "uuid" FROM "detections";
DROP TABLE "detections";
ALTER TABLE "_qb_tmp_detections" RENAME TO "detections";
CREATE UNIQUE INDEX IF NOT EXISTS "detections_uuid_unique" ON "detections" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_drones" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "farm_id" INTEGER REFERENCES "farms"("id"),
  "callsign" TEXT not null,
  "model" TEXT not null,
  "payload" TEXT CHECK ("payload" IN ('rgb', 'multispectral', 'thermal', 'lidar', 'hopper', 'speaker')) not null,
  "status" TEXT CHECK ("status" IN ('docked', 'in_flight', 'charging', 'maintenance', 'offline')) default 'docked',
  "station" TEXT,
  "battery_percent" INTEGER default 100,
  "flight_hours" INTEGER default 0,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_drones" ("id", "farm_id", "callsign", "model", "payload", "status", "station", "battery_percent", "flight_hours", "created_at", "updated_at", "uuid") SELECT "id", "farm_id", "callsign", "model", "payload", "status", "station", "battery_percent", "flight_hours", "created_at", "updated_at", "uuid" FROM "drones";
DROP TABLE "drones";
ALTER TABLE "_qb_tmp_drones" RENAME TO "drones";
CREATE UNIQUE INDEX IF NOT EXISTS "drones_callsign_unique" ON "drones" ("callsign");
CREATE UNIQUE INDEX IF NOT EXISTS "drones_uuid_unique" ON "drones" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
